# Generated by Django 3.2 on 2021-04-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210428_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivationtoken',
            old_name='user_id',
            new_name='user',
        ),
    ]
