# Generated by Django 3.2 on 2021-05-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AlterField(
            model_name='useractivationtoken',
            name='token',
            field=models.CharField(max_length=250),
        ),
    ]
