# Generated by Django 3.2 on 2021-05-06 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='phone'),
        ),
    ]
