# Generated by Django 3.2 on 2021-05-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_office_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='spots',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
