# Generated by Django 3.2 on 2021-05-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_office_spots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='addres',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='office',
            name='spots',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
