# Generated by Django 3.2 on 2021-05-12 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210512_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.office'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person'),
        ),
    ]
