# Generated by Django 3.2 on 2021-07-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_waiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_provider',
        ),
    ]
