# Generated by Django 3.2 on 2021-07-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_user_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('cancelled', 'cancelled'), ('ongoing', 'ongoing'), ('done', 'done')], default='ongoing', max_length=30),
        ),
    ]
