# Generated by Django 3.2.5 on 2021-08-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='county',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.county'),
            preserve_default=False,
        ),
    ]
