# Generated by Django 3.2 on 2021-08-07 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_person_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='county',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.county'),
            preserve_default=False,
        ),
    ]
