# Generated by Django 3.2.5 on 2021-08-08 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_office_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='hourlyLimit',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
