# Generated by Django 3.2 on 2021-08-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210808_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='addres',
            new_name='address',
        ),
    ]
