# Generated by Django 3.2 on 2021-08-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_appointment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('anulată', 'anulată'), ('în curs', 'în curs'), ('finalizată', 'finalizată')], default='ongoing', max_length=30),
        ),
    ]
