# Generated by Django 3.2.5 on 2021-08-15 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
    ]
