# Generated by Django 3.2 on 2021-08-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_appointment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('anulata', 'anulata'), ('în curs', 'în curs'), ('finalizata', 'finalizata')], default='în curs', max_length=30),
        ),
        migrations.AlterField(
            model_name='waiting',
            name='spot',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
