# Generated by Django 3.2 on 2021-08-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20210816_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('anulata', 'anulata'), ('in curs', 'in curs'), ('finalizata', 'finalizata')], default='in curs', max_length=30),
        ),
    ]
