# Generated by Django 3.2 on 2021-09-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20210831_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='kind',
            field=models.CharField(choices=[('prima doza', 'prima doza'), ('rapel', 'rapel'), ('doza unica', 'doza unica')], max_length=30),
        ),
    ]
